// Generated by ReScript, PLEASE EDIT WITH CARE


var HeadersInit = {};

var make = (()=> new Headers());

var makeWithInit = (init => new Headers(init));

var append = ((headers, name, value) => headers.append(name, value));

var $$delete = ((headers, name) => headers.delete(name));

var get = ((headers, name) => headers.get(name) ?? undefined);

var has = ((headers, name) => headers.has(name));

var set = ((headers, name, value) => headers.set(name, value));

var entries = (headers => headers.entries());

var keys = (headers => headers.keys());

var values = (headers => headers.values());

var forEach = ((headers, callback) => headers.forEach(callback));

var toJSON = (headers => headers.toJSON());

var count = (headers => headers.count);

var getAllCookies = (headers => headers.getAll("Set-Cookie"));

var $$Headers = {
  make: make,
  makeWithInit: makeWithInit,
  append: append,
  $$delete: $$delete,
  get: get,
  has: has,
  set: set,
  entries: entries,
  keys: keys,
  values: values,
  forEach: forEach,
  toJSON: toJSON,
  count: count,
  getAllCookies: getAllCookies
};

var headers = make();

append(headers, "Set-Cookie", "foo=bar");

var cookie = get(headers, "Set-Cookie");

var cookies = getAllCookies(headers);

var Test = {
  headers: headers,
  cookie: cookie,
  cookies: cookies
};

export {
  HeadersInit ,
  $$Headers ,
  Test ,
}
/* headers Not a pure module */
