// Generated by ReScript, PLEASE EDIT WITH CARE


var HeadersInit = {};

var make = (()=> new Headers());

var makeWithInit = (init => new Headers(init));

var append = ((headers, name, value) => headers.append(name, value));

var $$delete = ((headers, name) => headers.delete(name));

var $$Headers = {
  make: make,
  makeWithInit: makeWithInit,
  append: append,
  $$delete: $$delete
};

var headers = make();

append(headers, "Set-Cookie", "foo=bar");

var Test = {
  headers: headers
};

export {
  HeadersInit ,
  $$Headers ,
  Test ,
}
/* headers Not a pure module */
